# Generated by Django 4.2.7 on 2025-09-19 11:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_iso2', models.CharField(max_length=2, unique=True)),
                ('code_iso3', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('sub_region', models.CharField(blank=True, max_length=50)),
                ('continent', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_year_range_start', models.IntegerField(default=2020)),
                ('default_year_range_end', models.IntegerField(default=2024)),
                ('preferred_visualization', models.CharField(choices=[('CHOROPLETH', 'Choropleth Map'), ('FLOW', 'Flow Map'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('favorite_countries', models.ManyToManyField(blank=True, to='core.country')),
                ('favorite_sectors', models.ManyToManyField(blank=True, to='core.sector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTotalCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('total_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('flow_rank_global', models.IntegerField(blank=True, null=True)),
                ('flow_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capitaltype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
            ],
            options={
                'ordering': ['-year', '-total_inflow'],
                'indexes': [models.Index(fields=['year', 'sector'], name='core_countr_year_cefce5_idx'), models.Index(fields=['country', 'year'], name='core_countr_country_f74021_idx')],
                'unique_together': {('country', 'sector', 'capital_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CapitalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)])),
                ('quarter', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency_original', models.CharField(default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('data_source', models.CharField(max_length=100)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capitaltype')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='core.country')),
                ('target_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='core.country')),
            ],
            options={
                'ordering': ['-year', '-quarter', '-month'],
                'indexes': [models.Index(fields=['year', 'sector', 'capital_type'], name='core_capita_year_e480cd_idx'), models.Index(fields=['source_country', 'target_country'], name='core_capita_source__bc3a17_idx'), models.Index(fields=['sector', 'year'], name='core_capita_sector__18de23_idx')],
            },
        ),
    ]
