# Generated by Django 5.2.6 on 2025-09-21 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='자본 타입 코드')),
                ('name', models.CharField(max_length=100, verbose_name='자본 타입명')),
                ('name_en', models.CharField(max_length=100, verbose_name='영문명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '자본 타입',
                'verbose_name_plural': '자본 타입',
                'db_table': 'capital_types',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='국가 코드(ISO-3166)')),
                ('name', models.CharField(max_length=100, verbose_name='국가명')),
                ('name_en', models.CharField(max_length=100, verbose_name='영문명')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='지역')),
                ('continent', models.CharField(blank=True, max_length=30, verbose_name='대륙')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='소스명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('source_type', models.CharField(choices=[('OFFICIAL', '공식 기관'), ('PRIVATE_DB', '민간 데이터베이스'), ('CRAWLER', '크롤링'), ('API', '외부 API')], max_length=20, verbose_name='소스 타입')),
                ('reliability_level', models.CharField(choices=[('HIGH', '높음 (0.8-1.0)'), ('MEDIUM', '중간 (0.5-0.8)'), ('LOW', '낮음 (0.0-0.5)')], max_length=10, verbose_name='신뢰도 수준')),
                ('reliability_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='신뢰도 가중치')),
                ('api_endpoint', models.URLField(blank=True, null=True, verbose_name='API 엔드포인트')),
                ('update_frequency', models.CharField(blank=True, max_length=50, verbose_name='업데이트 주기')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '데이터 소스',
                'verbose_name_plural': '데이터 소스',
                'db_table': 'data_sources',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='분야 코드')),
                ('name', models.CharField(max_length=100, verbose_name='분야명')),
                ('name_en', models.CharField(max_length=100, verbose_name='영문명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.sector', verbose_name='상위 분야')),
            ],
            options={
                'verbose_name': '분야',
                'verbose_name_plural': '분야',
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='RawCapitalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('raw_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='원본 금액')),
                ('raw_currency', models.CharField(default='USD', max_length=3, verbose_name='원본 통화')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='USD 환산 금액')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='환율')),
                ('collection_date', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('data_quality_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='데이터 품질 점수')),
                ('is_outlier', models.BooleanField(default=False, verbose_name='이상치 여부')),
                ('is_verified', models.BooleanField(default=False, verbose_name='검증 완료')),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.capitaltype', verbose_name='자본 타입')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country', verbose_name='국가')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.datasource', verbose_name='데이터 소스')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sector', verbose_name='분야')),
            ],
            options={
                'verbose_name': '원시 자본 데이터',
                'verbose_name_plural': '원시 자본 데이터',
                'db_table': 'raw_capital_data',
            },
        ),
        migrations.CreateModel(
            name='ProcessedCapitalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('final_amount_usd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='최종 USD 금액')),
                ('fusion_method', models.CharField(choices=[('WEIGHTED_AVG', '가중평균'), ('ML_ENSEMBLE', 'ML 앙상블'), ('MEDIAN', '중간값'), ('SINGLE_SOURCE', '단일 소스')], max_length=20, verbose_name='융합 방법')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='신뢰도 점수')),
                ('source_count', models.PositiveIntegerField(verbose_name='참여 소스 수')),
                ('variance', models.FloatField(blank=True, null=True, verbose_name='소스 간 분산')),
                ('is_predicted', models.BooleanField(default=False, verbose_name='예측값 여부')),
                ('prediction_model', models.CharField(blank=True, max_length=50, verbose_name='예측 모델명')),
                ('processing_date', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('capital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.capitaltype', verbose_name='자본 타입')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country', verbose_name='국가')),
                ('raw_data_refs', models.ManyToManyField(blank=True, to='data.rawcapitaldata', verbose_name='참조 원시 데이터')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sector', verbose_name='분야')),
            ],
            options={
                'verbose_name': '정제된 자본 데이터',
                'verbose_name_plural': '정제된 자본 데이터',
                'db_table': 'processed_capital_data',
            },
        ),
        migrations.CreateModel(
            name='DataProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_type', models.CharField(choices=[('COLLECTION', '데이터 수집'), ('CLEANING', '데이터 정제'), ('FUSION', '데이터 융합'), ('VALIDATION', '데이터 검증'), ('PREDICTION', '값 예측')], max_length=20, verbose_name='처리 타입')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패'), ('PARTIAL', '부분 성공')], max_length=10, verbose_name='상태')),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='처리된 레코드 수')),
                ('records_success', models.PositiveIntegerField(default=0, verbose_name='성공 레코드 수')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='실패 레코드 수')),
                ('start_time', models.DateTimeField(verbose_name='시작시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료시간')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='소요시간(초)')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.datasource')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.sector')),
            ],
            options={
                'verbose_name': '데이터 처리 로그',
                'verbose_name_plural': '데이터 처리 로그',
                'db_table': 'data_processing_logs',
            },
        ),
        migrations.AddIndex(
            model_name='rawcapitaldata',
            index=models.Index(fields=['country', 'sector', 'year'], name='raw_capital_country_523f65_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcapitaldata',
            index=models.Index(fields=['capital_type', 'year'], name='raw_capital_capital_0878cc_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcapitaldata',
            index=models.Index(fields=['collection_date'], name='raw_capital_collect_b58df8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawcapitaldata',
            unique_together={('source', 'country', 'sector', 'capital_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='processedcapitaldata',
            index=models.Index(fields=['country', 'sector', 'year'], name='processed_c_country_fd459f_idx'),
        ),
        migrations.AddIndex(
            model_name='processedcapitaldata',
            index=models.Index(fields=['capital_type', 'year'], name='processed_c_capital_48ffc3_idx'),
        ),
        migrations.AddIndex(
            model_name='processedcapitaldata',
            index=models.Index(fields=['confidence_score'], name='processed_c_confide_6c055f_idx'),
        ),
        migrations.AddIndex(
            model_name='processedcapitaldata',
            index=models.Index(fields=['processing_date'], name='processed_c_process_01d440_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processedcapitaldata',
            unique_together={('country', 'sector', 'capital_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='dataprocessinglog',
            index=models.Index(fields=['processing_type', 'status'], name='data_proces_process_6fac73_idx'),
        ),
        migrations.AddIndex(
            model_name='dataprocessinglog',
            index=models.Index(fields=['start_time'], name='data_proces_start_t_2219bc_idx'),
        ),
    ]
