# Generated by Django 5.2.6 on 2025-10-09 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcapitaldata',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='신뢰도 점수'),
        ),
        migrations.AddField(
            model_name='rawcapitaldata',
            name='estimation_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='추정 방법'),
        ),
        migrations.AddField(
            model_name='rawcapitaldata',
            name='is_estimated',
            field=models.BooleanField(default=False, verbose_name='추정 데이터 여부'),
        ),
    ]
