# Generated by Django 5.2.6 on 2025-10-11 16:05

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_country_latitude_country_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('country', models.CharField(blank=True, max_length=10, null=True, verbose_name='국가 코드')),
                ('sector', models.CharField(blank=True, max_length=50, null=True, verbose_name='분야')),
                ('capital_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='자본 타입')),
                ('title', models.TextField(verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('url', models.URLField(verbose_name='URL')),
                ('source', models.CharField(max_length=100, verbose_name='출처')),
                ('published_at', models.DateTimeField(verbose_name='발행일시')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('relevance_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='관련도 점수')),
                ('search_query', models.CharField(max_length=200, verbose_name='검색 쿼리')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '뉴스 데이터',
                'verbose_name_plural': '뉴스 데이터',
                'db_table': 'news_data',
                'indexes': [models.Index(fields=['year', 'sector', 'capital_type'], name='news_data_year_0dcb8a_idx'), models.Index(fields=['year', 'country'], name='news_data_year_cd4a71_idx'), models.Index(fields=['collected_at'], name='news_data_collect_727fa4_idx')],
            },
        ),
    ]
